language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - pecl install swoole
  - composer install --dev

script: vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
